# Generated by Django 4.0.1 on 2022-01-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measuring',
        ),
    ]
