# Generated by Django 4.0.1 on 2022-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_measuring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='mainapp.CartProduct', verbose_name='Товары'),
        ),
    ]
