# Generated by Django 4.0.1 on 2022-01-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
