# Generated by Django 4.0.1 on 2022-01-13 06:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_order_address_order_address1_order_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SM', 'Самовывоз'), ('DL', 'Доставка')], default='SM', max_length=255, verbose_name='Тип получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
